codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree,reach
  show_carryforward_flags: false
coverage:
  precision: 2
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        informational: true
    project: true
github_checks:
  annotations: true
slack_app: true
