[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.check-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.doc]
install_crate = "doc"
env = { "RUSTDOCFLAGS" = "-D warnings" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.coverage-report]
description = "Shows you a coverage report"
workspace = false
command = "cargo"
args = [
    "llvm-cov",
    "--workspace",
]

[tasks.codecov-coverage]
description = "Generate Codecov coverage report"
workspace = false
command = "cargo"
args = [
    "llvm-cov",
    "--workspace",
    "--codecov",
    "--output-path",
    "target/codecov.json",
]

[tasks.checks]
dependencies = [
    "check-format",
    "build",
    "test",
    "clippy",
    "doc",
]

[tasks.counter-example-svg]
workspace = false
command = "svg-term"
args = [
    "--out", "examples/images/counter.svg",
    "--window",
    "--width", "60",
    "--height", "4",
    "--no-cursor",
    "--command",
    "echo '\\033[0;37miocraft\\033[0m % \\033[0;32mcargo\\033[0m run -q --example counter' && timeout 10s cargo run -q --example counter",
]
