name: Push
on: [push]
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.80.1
        components: clippy
    - name: Build
      run: cargo build --all --examples
    - name: Test
      run: cargo test --all
    - name: Clippy
      run: cargo clippy --all -- -D warnings
